apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  namespace: art-tools
  metadata:
    labels:
      build: ocp-build-data-validator
    name: ocp-build-data-validator
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/centos/centos:stream8
      from:
        kind: DockerImage
        name: quay.io/centos/centos:stream8
      generation: null
      importPolicy: {}
      name: centos-stream8
      referencePolicy:
        type: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  namespace: art-tools
  metadata:
    labels:
      build: ocp-build-data-validator-base
    name: ocp-build-data-validator-base
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ocp-build-data-validator:base
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/openshift/ocp-build-data-validator
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ocp-build-data-validator:centos-stream8
        dockerfilePath: deploy/Dockerfile.base
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
