kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  data:
    WebHookSecretKey: CHANGEME=
  kind: Secret
  metadata:
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:WebHookSecretKey: {}
        f:type: {}
      manager: Mozilla
      operation: Update
    name: ocp-build-data-validator-webhook
    namespace: art-tools
    selfLink: /api/v1/namespaces/art-tools/secrets/ocp-build-data-validator-webhook
  type: Opaque
- apiVersion: v1
  data:
    .dockerconfigjson: CHANGEME==
  kind: Secret
  metadata:
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:type: {}
      manager: Mozilla
      operation: Update
    name: quay-io-openshift-art-psi-image-builder-auth
    namespace: art-tools
    selfLink: /api/v1/namespaces/art-tools/secrets/quay-io-openshift-art-psi-image-builder-auth
  type: kubernetes.io/dockerconfigjson
